<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>MiLifeDeviceCollector</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.0.0</Version>
    <PublishTrimmed>false</PublishTrimmed>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../MiLife.DeviceContracts/MiLife.DeviceContracts.csproj" />
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    <EmbeddedResource Include="collector-settings.json" Condition="Exists('collector-settings.json')" LogicalName="CollectorSettings" />
  </ItemGroup>
</Project>
