// <auto-generated />
using System;
using MiLife.DeviceIntake.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiLife.DeviceIntake.Api.Data.MySqlMigrations
{
    [DbContext(typeof(MySqlIntakeDbContext))]
    [Migration("20260918121707_AgentLifecycle")]
    partial class AgentLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_bin")
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.AgentAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Error")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "RequestedAtUtc");

                    b.ToTable("AgentActions");
                });

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.DeviceAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double?>("AccuracyMeters")
                        .HasColumnType("double");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("CredentialHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("EmployeeName")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime>("EnrolledAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<DateTime?>("LocationCapturedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber", "LastSeenAtUtc");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.DeviceIdentity", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SerialNumber");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.DeviceSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CollectorVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ComputerName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("DisksJson")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsRepeat")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LoggedInUser")
                        .HasColumnType("longtext");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<string>("NetworkJson")
                        .HasColumnType("longtext");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ProcessorJson")
                        .HasColumnType("longtext");

                    b.Property<double?>("RamGB")
                        .HasColumnType("double");

                    b.Property<string>("RamJson")
                        .HasColumnType("longtext");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("WindowsJson")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BranchCode");

                    b.HasIndex("CollectionId")
                        .IsUnique();

                    b.HasIndex("ComputerName");

                    b.HasIndex("SerialNumber", "ReceivedAtUtc");

                    b.HasIndex("Status", "ReceivedAtUtc");

                    b.ToTable("DeviceSubmissions");
                });

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.SubmissionReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("ReviewedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Reviewer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.SupportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Output")
                        .HasMaxLength(16000)
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "RequestedAtUtc");

                    b.ToTable("SupportJobs");
                });

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.AgentAction", b =>
                {
                    b.HasOne("MiLife.DeviceIntake.Api.Models.DeviceAgent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.DeviceAgent", b =>
                {
                    b.HasOne("MiLife.DeviceIntake.Api.Models.DeviceIdentity", "Device")
                        .WithMany()
                        .HasForeignKey("SerialNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.DeviceSubmission", b =>
                {
                    b.HasOne("MiLife.DeviceIntake.Api.Models.DeviceIdentity", "Device")
                        .WithMany()
                        .HasForeignKey("SerialNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.SubmissionReview", b =>
                {
                    b.HasOne("MiLife.DeviceIntake.Api.Models.DeviceSubmission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.SupportJob", b =>
                {
                    b.HasOne("MiLife.DeviceIntake.Api.Models.DeviceAgent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");
                });
#pragma warning restore 612, 618
        }
    }
}
