// <auto-generated />
using System;
using MiLife.DeviceIntake.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiLife.DeviceIntake.Api.Data.Migrations
{
    [DbContext(typeof(IntakeDbContext))]
    [Migration("20260918121650_AgentLifecycle")]
    partial class AgentLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.AgentAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "RequestedAtUtc");

                    b.ToTable("AgentActions");
                });

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.DeviceAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AccuracyMeters")
                        .HasColumnType("REAL");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnrolledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("LocationCapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber", "LastSeenAtUtc");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.DeviceIdentity", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("SerialNumber");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.DeviceSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectorVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ComputerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisksJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRepeat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoggedInUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("NetworkJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessorJson")
                        .HasColumnType("TEXT");

                    b.Property<double?>("RamGB")
                        .HasColumnType("REAL");

                    b.Property<string>("RamJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchCode");

                    b.HasIndex("CollectionId")
                        .IsUnique();

                    b.HasIndex("ComputerName");

                    b.HasIndex("SerialNumber", "ReceivedAtUtc");

                    b.HasIndex("Status", "ReceivedAtUtc");

                    b.ToTable("DeviceSubmissions");
                });

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.SubmissionReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReviewedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reviewer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.SupportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Output")
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "RequestedAtUtc");

                    b.ToTable("SupportJobs");
                });

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.AgentAction", b =>
                {
                    b.HasOne("MiLife.DeviceIntake.Api.Models.DeviceAgent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.DeviceAgent", b =>
                {
                    b.HasOne("MiLife.DeviceIntake.Api.Models.DeviceIdentity", "Device")
                        .WithMany()
                        .HasForeignKey("SerialNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.DeviceSubmission", b =>
                {
                    b.HasOne("MiLife.DeviceIntake.Api.Models.DeviceIdentity", "Device")
                        .WithMany()
                        .HasForeignKey("SerialNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.SubmissionReview", b =>
                {
                    b.HasOne("MiLife.DeviceIntake.Api.Models.DeviceSubmission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("MiLife.DeviceIntake.Api.Models.SupportJob", b =>
                {
                    b.HasOne("MiLife.DeviceIntake.Api.Models.DeviceAgent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");
                });
#pragma warning restore 612, 618
        }
    }
}
